import * as React from 'react';
import './style.scss';

interface Props {
  onChatMessageSend?: (message: string) => void;
  userId?: string;
  scrollToBottomHandler?: () => void;
}

const EnhancedChatPanel: React.FC<Props> = ({
  onChatMessageSend,
  userId = 'anonymous',
  scrollToBottomHandler
}) => {
  const [message, setMessage] = React.useState<string>('');
  const [chatHistory, setChatHistory] = React.useState<Array<{
    type: 'system' | 'user' | 'assistant';
    text: string;
    timestamp: number;
  }>>([
    {
      type: 'system',
      text: 'Welcome to Policy Maps Chat! Ask questions about maps, data layers, or specific geographic areas.',
      timestamp: Date.now()
    }
  ]);
  
  const [isLoading, setIsLoading] = React.useState<boolean>(false);
  
  const chatContainerRef = React.useRef<HTMLDivElement>(null);
  
  // Scroll to bottom of chat when history changes
  React.useEffect(() => {
    if (chatContainerRef.current) {
      chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
    }
    
    if (scrollToBottomHandler) {
      scrollToBottomHandler();
    }
  }, [chatHistory, scrollToBottomHandler]);
  
  const handleMessageChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setMessage(e.target.value);
  };
  
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!message.trim() || isLoading) return;
    
    // Add user message to chat history
    const userMessage = {
      type: 'user' as const,
      text: message,
      timestamp: Date.now()
    };
    
    setChatHistory(prev => [...prev, userMessage]);
    
    // Call the onChatMessageSend callback if provided
    if (onChatMessageSend) {
      onChatMessageSend(message);
    }
    
    // Clear the input
    setMessage('');
    
    // Set loading state
    setIsLoading(true);
    
    try {
      // Simulate a response for now
      // In a real implementation, this would call Azure OpenAI
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      // Add assistant message to chat history
      setChatHistory(prev => [
        ...prev,
        {
          type: 'assistant',
          text: `This is a simulated response to your message: "${message}". In the actual implementation, this would be generated by Azure OpenAI.`,
          timestamp: Date.now()
        }
      ]);
    } catch (error) {
      console.error('Error sending message:', error);
      
      // Add error message to chat history
      setChatHistory(prev => [
        ...prev,
        {
          type: 'assistant',
          text: 'Sorry, I encountered an error while processing your request. Please try again later.',
          timestamp: Date.now()
        }
      ]);
    } finally {
      // Clear loading state
      setIsLoading(false);
    }
  };
  
  // Function to format timestamp
  const formatTime = (timestamp: number): string => {
    const date = new Date(timestamp);
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };
  
  return (
    <div className="enhanced-chat-panel">
      <div className="chat-history" ref={chatContainerRef}>
        {chatHistory.map((msg, index) => (
          <div key={index} className={`chat-message ${msg.type}`}>
            <div className="message-content">
              <span className="message-text">{msg.text}</span>
              <span className="message-time">{formatTime(msg.timestamp)}</span>
            </div>
          </div>
        ))}
        
        {/* Show typing indicator when loading */}
        {isLoading && (
          <div className="chat-message assistant">
            <div className="message-content typing-indicator">
              <span className="dot"></span>
              <span className="dot"></span>
              <span className="dot"></span>
            </div>
          </div>
        )}
      </div>
      
      <form onSubmit={handleSubmit} className="chat-input-form">
        <div className="chat-input-container">
          <textarea
            className="chat-input"
            placeholder="Ask about maps, data layers, or geographic areas..."
            value={message}
            onChange={handleMessageChange}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                handleSubmit(e);
              }
            }}
            disabled={isLoading}
          />
          <button type="submit" className="send-button" disabled={isLoading}>
            <span className="icon-ui-send"></span>
          </button>
        </div>
        <div className="chat-input-help">
          Press Enter to send, Shift+Enter for new line
        </div>
      </form>
    </div>
  );
};

export default EnhancedChatPanel;
